### ISSUE TITLE
Track toevoegen

### ISSUE THREAD

**Issue by hiddebraun-ma** [MiloDijkman/bap-md1-periode-3#2]
Ik mis de link naar het formulier voor het toevoegen van een track en het opslaan van de track met een (prepared) SQL INSERT statement.

Hulp: http://bap.mediadeveloper.amsterdam/md1/periode-3/lesstof-en-extra-informatie/sql-refresh/#insert

https://github.com/MiloDijkman/bap-md1-periode-3/blob/7ce7829cb252a2bf47e87354f66185828aac4e16/02-sql-refresh-1/index.php#L40

**Comment by MiloDijkman** [comment]
Beste Hidde Braun,

Als u hiermee de 2de opdracht bedoeld dan staat die opdracht er wel in
https://github.com/MiloDijkman/bap-md1-periode-3

**Comment by hiddebraun-ma** [comment]
Nog niet in Github, maar dat komt dan nog als je Git weer werkt.
