### ISSUE TITLE
Melding of bedanktpagina

### ISSUE THREAD

**Issue by hiddebraun-ma** [MiloDijkman/bap-md1-periode-3#6]
https://github.com/MiloDijkman/bap-md1-periode-3/blob/efd6ea6f60ffdcf95a53fabc8c27586e2ec169e4/04-sql-register-3/save_user.php#L43

Misschien mooier als je de gebruiker feedback geeft over of de registratie gelukt is?
Of doorsturen naar een bedankt pagina. Nu lijkt het of het niet is gelukt omdat het ik op een leeg formulier terug kom.

**Comment by MiloDijkman** [comment]
Ik heb net alles gepushed en algoed is staat alles daar!


________________________________
Van: Hidde Braun <notifications@github.com>
Verzonden: Thursday, March 5, 2020 12:19:21 PM
Aan: MiloDijkman/bap-md1-periode-3 <bap-md1-periode-3@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [MiloDijkman/bap-md1-periode-3] Melding of bedanktpagina (#6)


https://github.com/MiloDijkman/bap-md1-periode-3/blob/efd6ea6f60ffdcf95a53fabc8c27586e2ec169e4/04-sql-register-3/save_user.php#L43<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMiloDijkman%2Fbap-md1-periode-3%2Fblob%2Fefd6ea6f60ffdcf95a53fabc8c27586e2ec169e4%2F04-sql-register-3%2Fsave_user.php%23L43&data=02%7C01%7C29147%40ma-web.nl%7Cdaa51fa447644892b21608d7c0f70eb0%7C8e600f9230df4667b7c03f2595f3f12b%7C0%7C0%7C637190039648016932&sdata=JTrchML8Wnay74hobdGE1oT4s363H%2BbQGOvPwFBCHGk%3D&reserved=0>

Misschien mooier als je de gebruiker feedback geeft over of de registratie gelukt is?
Of doorsturen naar een bedankt pagina. Nu lijkt het of het niet is gelukt omdat het ik op een leeg formulier terug kom.
